comment "Exported from Arsenal by [-GSRI-] Lisitius";

comment "Remove existing items";
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;

comment "Add containers";
player forceAddUniform "VSM_G2_camo_MultiCam";
player addItemToUniform "ACE_EarPlugs";
player addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_CableTie";};
for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
for "_i" from 1 to 15 do {player addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_Chemlight_White";};
player addItemToUniform "SMA_30Rnd_556x45_Mk318";
player addItemToUniform "B_IR_Grenade";
player addVest "VSM_MBSS_PACA_BattleBelt_operator";
for "_i" from 1 to 10 do {player addItemToVest "ACE_packingBandage";};
for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
for "_i" from 1 to 3 do {player addItemToVest "ACE_morphine";};
for "_i" from 1 to 3 do {player addItemToVest "ACE_epinephrine";};
for "_i" from 1 to 15 do {player addItemToVest "ACE_elasticBandage";};
for "_i" from 1 to 2 do {player addItemToVest "ACE_tourniquet";};
for "_i" from 1 to 15 do {player addItemToVest "ACE_salineIV_500";};
for "_i" from 1 to 2 do {player addItemToVest "ACE_atropine";};
for "_i" from 1 to 6 do {player addItemToVest "SMA_30Rnd_556x45_Mk262";};
for "_i" from 1 to 4 do {player addItemToVest "SmokeShell";};
player addItemToVest "ACE_M84";
player addItemToVest "HandGrenade";
player addItemToVest "SmokeShellBlue";
player addBackpack "SOG_BAG_med_od";
for "_i" from 1 to 11 do {player addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 15 do {player addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 5 do {player addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 5 do {player addItemToBackpack "ACE_quikclot";};
for "_i" from 1 to 4 do {player addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 4 do {player addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 4 do {player addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 3 do {player addItemToBackpack "ACE_atropine";};
for "_i" from 1 to 2 do {player addItemToBackpack "adv_aceSplint_splint";};
player addItemToBackpack "ACE_surgicalKit";
player addHeadgear "Booniehat_CE_hs";

comment "Add weapons";
player addWeapon "SMA_MK18MOEBLKTAN_SM";
player addPrimaryWeaponItem "SMA_rotex_blk";
player addPrimaryWeaponItem "SMA_SFFL_BLK";
player addPrimaryWeaponItem "optic_ERCO_blk_F";
player addPrimaryWeaponItem "SMA_Gripod_01";
player addWeapon "hgun_Rook40_F";
player addHandgunItem "muzzle_snds_L";

comment "Add items";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "TFAR_anprc152";
