name: release

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: [ 'CONT_Orion.Malden/**' ]

jobs:
  release:
    runs-on: [self-hosted, arma-tools]
    steps:

      - name: Checkout files
        uses: actions/checkout@v3
        
      - name: Get new version
        id: new-version
        uses: arwynfr/actions-conventional-versioning@0.3.1
        with:
            pattern: $(Convert-Path *.pbo)
            whatif: '$true'
            
      - name: Make mission pbo
        uses: team-gsri/actions-build-mission@0.1.1
        with:
          briefingName: 'Orion ${{ steps.new-version.outputs.next-version }}'
          source: ./CONT_Orion.Malden
          target: ./

      - name: Upload PBO to github
        uses: actions/upload-artifact@v3
        with:
          name: mission
          path: ./*.pbo

      - name: Create Github Release
        uses: arwynfr/actions-conventional-versioning@0.3.1
        with:
            pattern: $(Convert-Path *.pbo)