name: release

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['CONT_Orion.Malden/**']

jobs:
  release:
    runs-on: [self-hosted, arma-tools]
    steps:

      - name: Make mission pbo
        uses: team-gsri/actions-arma-tools/release-mission@0.0.3
        with:
          missionName: Orion
          source: ./CONT_Orion.Malden
