name: release

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: [ 'CONT_Orion.Malden/**' ]

jobs:
  release:
    runs-on: [self-hosted, arma-tools]
    steps:

      - name: Checkout files
        uses: actions/checkout@v2

      - name: Make mission pbo
        uses: team-gsri/actions-build-mission@0.0.1
        with:
          source: ./CONT_Orion.Malden
          target: ./

      - name: Upload PBO to github
        uses: actions/upload-artifact@v3
        with:
          name: mission
          path: ./*.pbo

      - name: Create Github Release
        uses: arwynfr/actions-conventional-versioning@0.1.0
        with:
            pattern: $(Convert-Path *.pbo)